# Generated by Django 4.2.5 on 2023-10-09 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_remove_adressbook_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='referral_id',
            field=models.CharField(blank=True, default='', max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='username',
            field=models.CharField(max_length=50),
        ),
    ]
