# Generated by Django 4.2.5 on 2023-10-09 16:27

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_account_referral_id_alter_account_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='referral_id',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
